---
- name: configure server
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: partition-disk
      tags: partition-disk

    - role: bridge-network-create
      tags: bridge-network-create

    - role: bridge-network-destroy
      tags: bridge-network-destroy


    - role: kvm-install
      tags: kvm-install

    - role: rhel-vm-create
      tags: rhel-vm-create

    - role: rhel-vm-destroy
      tags: rhel-vm-destroy
